version: '3.8'

services:
  rss_monitor:
    image: smhw3565/rss_monitor:latest
    container_name: rss_monitor
    restart: unless-stopped
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:-}
      - TG_CHAT_ID=${TG_CHAT_ID:-}
      - TZ=Asia/Shanghai
      - CHECK_MIN_INTERVAL=${CHECK_MIN_INTERVAL:-30}
      - CHECK_MAX_INTERVAL=${CHECK_MAX_INTERVAL:-60}
    volumes:
      - ./data:/data
    networks:
      - rss-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f rss_main.py || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  rss-network:
    driver: bridge
