version: '3.8'

services:
  rss_nodeseek:
    image: smhw3565/rss_nodeseek:rss
    container_name: rss_nodeseek
    restart: unless-stopped
    environment:
      # Telegram配置（可以通过环境变量设置）
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:-}
      - TG_CHAT_ID=${TG_CHAT_ID:-}
      # 时区设置
      - TZ=Asia/Shanghai
    volumes:
      # 数据持久化
      - ./data:/data
    # 网络配置
    networks:
      - rss-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  rss-network:
    driver: bridge

 